name: new_insta_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_icon.png # Use a .png file for native splash screen
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
